apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: norah-ns
  labels: 
    app: myapppod
spec:
  containers:
    - name: myapp-container
      image: norahbiju/flowerwebapp:v2
      ports:
        - containerPort: 3000
