apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: cart-rs
  namespace: norah-ns
  labels:
    app: cart
spec: #defines the behaviour of the ReplicaSet
  replicas: 3
  selector:
    matchLabels:
      app: web
  template: # it contains pod defination
    metadata:
      labels:
        app: web 
    spec: # container defination
      containers:
        - name: cart-container
          image: muralisocial123/flipkart-app-web:v1.1.0
          ports:
            - containerPort: 3000
